name: CI

on: push

jobs:
  ci:
    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: '1.12'
              otp: '23.3'
              postgres: '12.13-alpine'
            exclude_tags: 'search'
          - pair:
              elixir: '1.14'
              otp: '25.1'
              postgres: '15.1-alpine'
            lint: lint
            exclude_tags: 'nothing'

    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:${{matrix.pair.postgres}}
        env:
          POSTGRES_DB: oban_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-

      - name: Authorize with Oban
        env:
          OBAN_KEY_SHA: ${{secrets.oban_key_sha}}
          OBAN_API_KEY: ${{secrets.oban_api_key}}
        run: mix hex.repo add oban https://getoban.pro/repo --fetch-public-key $OBAN_KEY_SHA --auth-key $OBAN_API_KEY

      - name: Run mix deps.get
        run: mix deps.get

      - name: Run mix format
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Run mix deps.compile
        run: mix deps.compile

      - name: Run mix compile
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run credo
        run: mix credo --strict
        if: ${{ matrix.lint }}

      - name: Run mix ecto.migrate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/oban_test
        run: mix test.setup

      - name: Run mix test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:${{job.services.postgres.ports[5432]}}/oban_test
        run: mix test --exclude ${{ matrix.exclude_tags }}
